name: Flask Application CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # The private key stored in GitHub Secrets
          port: ${{ secrets.PORT }}
          script: |
            docker stop jenkins || true
            docker rm jenkins || true
            docker build -t jenkins /home/r0han01/Super-Interactive-Flask-Webpage
            docker run --name jenkins -d -p 9000:9000 jenkins
